=== AWS Services

The core AWS components used by this Quick Start include the following AWS services. (If you
are new to AWS, see the https://aws.amazon.com/getting-started/[Getting Started section^]
of the AWS documentation.)

* http://aws.amazon.com/documentation/ec2/[Amazon EC2^] +
The Amazon Elastic Compute Cloud (Amazon EC2) service enables you to launch virtual machine
instances with a variety of operating systems. You can choose from existing Amazon Machine
Images (AMIs) or import your own virtual machine images.
* http://aws.amazon.com/documentation/vpc/[Amazon VPC^] +
The Amazon Virtual Private Cloud (Amazon VPC) service lets you provision a private,
isolated section of the AWS Cloud where you can launch AWS services and other resources
in a virtual network that you define. You have complete control over your virtual
networking environment, including selection of your own IP address range, subnet creation,
and configuration of route tables and network gateways.
* https://aws.amazon.com/quickstart/architecture/terraform-modules-on-aws/[Terraform-modules-on-aws^] +
You can now use Terraform modules on Amazon Web Services (AWS) to deploy native Terraform
resources on the AWS Cloud. Terraform modules on AWS are published under an open-source
license.
** Terraform modules on AWS are available in the Terraform registry on the 
https://registry.terraform.io/namespaces/aws-ia[AWS Integration and Automation namespace page^].
Use the links provided to access modules in the Terraform registry and source code on
GitHub. For module deployment instructions, refer to the README.md file in the GitHub
repository.
* https://aws.amazon.com/documentation/autoscaling/[Auto Scaling^] +
Auto Scaling helps maintain high availability and manage capacity by automatically
increasing or decreasing the EC2 instance fleet. You can use Auto Scaling to run your
fleet at optimal utilization by increasing instance capacity during demand spikes and
decreasing capacity during down times.
* http://aws.amazon.com/documentation/elastic-load-balancing/[Elastic Load Balancing^] +
Elastic Load Balancing automatically distributes incoming application traffic across
multiple EC2 instances.
* https://docs.aws.amazon.com/cloudfront/index.html[Amazon CloudFront] +
Amazon CloudFront is a web service that speeds up distribution of your static and
dynamic web content, such as .html, .css, .js, and image files, to your users.
CloudFront delivers your content through a worldwide network of data centers called
edge locations.
* https://aws.amazon.com/s3[Amazon Simple Storage Service (Amazon S3)^] +
Amazon S3 is an object storage service that offers industry-leading scalability,
data availability, security, and performance. This Magento deployment uses Amazon
S3 as https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage.html[Remote Storage Module^]
for Magento to provide the option to store media files and schedule imports/exports
in a persistent, remote storage container.
*Note*: https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage-aws-s3.html[Magento^] 
highly discourages the use of public buckets due to high security risks.
* https://aws.amazon.com/opensearch-service/the-elk-stack/what-is-elasticsearch/[Amazon OpenSearch Service^] +
Elasticsearch has quickly become the most popular search engine and is commonly used
for log analytics, full-text search, security intelligence, business analytics, and
operational intelligence use cases. As of version 2.4, Magento requires Elasticsearch
to be the catalog search engine. 
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-aws.html[Magento supports using Elasticsearch (ES)^]
provided by Amazon Web Services (AWS).
* https://aws.amazon.com/documentation/elasticache/[Amazon ElastiCache^] +
Amazon ElastiCache service makes it easy to deploy, operate, and scale an in-memory
data store or cache in
https://aws.amazon.com/what-is-cloud-computing/[the cloud^].
The service improves the performance of web applications by allowing you to retrieve
information from fast, managed, in-memory data stores, instead of relying entirely on
slower disk-based databases.
* https://docs.aws.amazon.com/amazon-mq/[Amazon MQ^] +
Amazon MQ is a managed message broker service that makes it easy to set up and operate
message brokers in the cloud. The MQF uses http://www.rabbitmq.com[RabbitMQ^] as the messaging
broker, which provides a scalable platform for sending and receiving messages. It also
includes a mechanism for storing undelivered messages. RabbitMQ are primarily needed for
B2B and async operations like import/export or Bulk operation.
* http://aws.amazon.com/documentation/rds/[Amazon RDS^] +
Amazon Relational Database Service (Amazon RDS) makes it easy to set up, operate, and
scale a growing set of relational databases, including MySQL and Amazon Aurora, both
of which are supported by the Magento Quick Start. With Amazon RDS, you can deploy
scalable relational databases in minutes with cost-efficient and resizable hardware
capacity.
* http://aws.amazon.com/documentation/iam/[IAM^] +
AWS Identity and Access Management (IAM) enables you to securely control access to
AWS services and resources for your users. With IAM, you can manage users, security
credentials such as access keys, and permissions that control which AWS resources users
can access, from a central location.

