=== AWS Services

The core AWS components used by this Quick Start include the following AWS services. (If you
are new to AWS, see the https://aws.amazon.com/getting-started/[Getting Started section^]
of the AWS documentation.)

* http://aws.amazon.com/documentation/ec2/[Amazon EC2^] +
The Amazon Elastic Compute Cloud (Amazon EC2) service enables you to launch virtual machine
instances with a variety of operating systems. You can choose from existing Amazon Machine
Images (AMIs) or import your own virtual machine images.
* http://aws.amazon.com/documentation/vpc/[Amazon VPC^] +
The Amazon Virtual Private Cloud (Amazon VPC) service lets you provision a private,
isolated section of the AWS Cloud where you can launch AWS services and other resources
in a virtual network that you define. You have complete control over your virtual
networking environment, including selection of your own IP address range, subnet creation,
and configuration of route tables and network gateways.
* https://aws.amazon.com/quickstart/architecture/terraform-modules-on-aws/[Terraform-modules-on-aws^] +
You can now use Terraform modules on Amazon Web Services (AWS) to deploy native Terraform
resources on the AWS Cloud. Terraform modules on AWS are published under an open-source
license.
** Terraform modules on AWS are available in the Terraform registry on the 
https://registry.terraform.io/namespaces/aws-ia[AWS Integration and Automation namespace page^].
Use the links provided to access modules in the Terraform registry and source code on
GitHub. For module deployment instructions, refer to the README.md file in the GitHub
repository.
* https://aws.amazon.com/documentation/autoscaling/[Auto Scaling^] +
Auto Scaling helps maintain high availability and manage capacity by automatically
increasing or decreasing the EC2 instance fleet. You can use Auto Scaling to run your
fleet at optimal utilization by increasing instance capacity during demand spikes and
decreasing capacity during down times.
* http://aws.amazon.com/documentation/elastic-load-balancing/[Elastic Load Balancing^] +
Elastic Load Balancing automatically distributes incoming application traffic across
multiple EC2 instances.
* https://docs.aws.amazon.com/cloudfront/index.html[Amazon CloudFront] +
Amazon CloudFront is a web service that speeds up distribution of your static and
dynamic web content, such as .html, .css, .js, and image files, to your users.
CloudFront delivers your content through a worldwide network of data centers called
edge locations.
* https://aws.amazon.com/s3[Amazon Simple Storage Service (Amazon S3)^] +
Amazon S3 is an object storage service that offers industry-leading scalability,
data availability, security, and performance. This Magento deployment uses Amazon
S3 as https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage.html[Remote Storage Module^]
for Magento to provide the option to store media files and schedule imports/exports
in a persistent, remote storage container.
*Note*: https://devdocs.magento.com/guides/v2.4/config-guide/remote-storage/config-remote-storage-aws-s3.html[Magento^] 
highly discourages the use of public buckets due to high security risks.
* https://aws.amazon.com/opensearch-service/the-elk-stack/what-is-elasticsearch/[Amazon OpenSearch Service^] +
Elasticsearch has quickly become the most popular search engine and is commonly used
for log analytics, full-text search, security intelligence, business analytics, and
operational intelligence use cases. As of version 2.4, Magento requires Elasticsearch
to be the catalog search engine. 
https://devdocs.magento.com/guides/v2.4/install-gde/prereq/es-aws.html[Magento supports using Elasticsearch (ES)^]
provided by Amazon Web Services (AWS).
* https://aws.amazon.com/documentation/elasticache/[Amazon ElastiCache^] +
Amazon ElastiCache service makes it easy to deploy, operate, and scale an in-memory
data store or cache in
https://aws.amazon.com/what-is-cloud-computing/[the cloud^].
The service improves the performance of web applications by allowing you to retrieve
information from fast, managed, in-memory data stores, instead of relying entirely on
slower disk-based databases.
* https://docs.aws.amazon.com/amazon-mq/[Amazon MQ^] +
Amazon MQ is a managed message broker service that makes it easy to set up and operate
message brokers in the cloud. The MQF uses http://www.rabbitmq.com[RabbitMQ^] as the messaging
broker, which provides a scalable platform for sending and receiving messages. It also
includes a mechanism for storing undelivered messages. RabbitMQ are primarily needed for
B2B and async operations like import/export or Bulk operation.
* http://aws.amazon.com/documentation/rds/[Amazon RDS^] +
Amazon Relational Database Service (Amazon RDS) makes it easy to set up, operate, and
scale a growing set of relational databases, including MySQL and Amazon Aurora, both
of which are supported by the Magento Quick Start. With Amazon RDS, you can deploy
scalable relational databases in minutes with cost-efficient and resizable hardware
capacity.
* http://aws.amazon.com/documentation/iam/[IAM^] +
AWS Identity and Access Management (IAM) enables you to securely control access to
AWS services and resources for your users. With IAM, you can manage users, security
credentials such as access keys, and permissions that control which AWS resources users
can access, from a central location.

=== Amazon Aurora and Amazon RDS for MySQL

By default, this Quick Start uses Amazon Aurora, but you can deploy Amazon RDS for
MySQL instead by setting a template parameter during deployment. If you choose Amazon
Aurora, but it is not available in the selected AWS Region (please check the 
https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/[region table^]),
you will not be able to launch the Quick Start. +
{blank} +
Amazon Aurora is a MySQL 5.6-compatible https://aws.amazon.com/relational-database/[relational database^]
engine that combines the speed and availability of high-end commercial databases with
the simplicity and cost-effectiveness of open source databases. It provides up to five
times better performance than MySQL, as well as the security, availability, and
reliability of a commercial database at one-tenth of the cost. See the
https://aws.amazon.com/rds/aurora/pricing/[Amazon Aurora Pricing^] page for further
details. +
{blank} +
Amazon RDS deployments are preconfigured with a set of parameters and settings appropriate
for the DB instance class you choose. Amazon RDS supports automatic software patching,
database backups, backup storage for a user-defined retention period, and point-in-time
recovery. +
{blank} +
Amazon RDS supports three types of storage: Magnetic, General Purpose (SSD), and
Provisioned IOPS (SSD). General Purpose (SSD) storage delivers a consistent baseline
of 3 IOPS per provisioned GiB and provides the ability to burst up to 3,000 IOPS.
To achieve a higher level of performance, consider using Provisioned IOPS (SSD) to
provision from 1,000 IOPS up to 30,000 IOPS per DB instance. (Maximum realized IOPS
may be lower.) You can provision up to 3 TiB storage and 30,000 IOPS per database
instance. We recommend using Magnetic storage for small database workloads where
data is accessed less frequently. Note that you can convert from standard storage to
Provisioned IOPS storage on a running cluster. (There is a short availability impact
on the servers.) +
{blank} +
To enhance availability and reliability for production workloads, you should use the
Multi-AZ deployment option. This provides an automated failover from the primary database
to a synchronously replicated secondary database that is running in a different Availability
Zone. This option also enables you to scale out beyond the capacity of a single database for
read-heavy database workloads.

=== Amazon EC2 Web Server Instances

The deployment installs NGINX on EC2 instances running Amazon Linux x86-64. Elastic Load
Balancing is used to automatically distribute the website load across these instances.
In addition, all the instances are launched in an Auto Scaling group that dynamically
manages the Amazon EC2 fleet. The deployment sets low and high CPU utilization thresholds
to automatically scale the number of EC2 instances up or down depending on load. Default
policy adds new instances when the CPU load exceeds 90% for 10 minutes, and removes
instances when the CPU load drops below 70% for 10 minutes. +
{blank} +
You can specify the maximum number of instances in the Auto Scaling group, and Auto
Scaling ensures that your group never goes above this size. You can also specify the
desired capacity, either when you create the group or at any time thereafter, and Auto
Scaling will ensure that your group has the desired number of instances. These options
are configurable during Quick Start launch. +
{blank} +
The Quick Start supports a variety of EC2 instance types. We recommend that you
benchmark the cluster to make sure you achieve the level of performance you need before
starting a production deployment. For high availability, we recommend using at least
two web server instances in different Availability Zones.

=== Amazon Simple Storage Service (Amazon S3)

When you deploy Magento with this Quick Start, Amazon S3 is configured as a Remote Storage
module. This provides the option to store media files and schedule imports/exports in a
persistent, remote storage container using a storage service. +
{blank} +
Amazon S3 is an object storage service with a simple interface that enables you to create
and configure storage quickly and easily. Multiple EC2 instances can access an Amazon S3
storage at the same time using the Magento remote storage option, providing a common data
source for workloads and applications running on more than one instance.

=== Amazon ElastiCache

Amazon ElastiCache is a web service that helps you deploy and operate an in-memory cache
in the AWS Cloud. This Quick Start automatically deploys an ElastiCache cluster using
the Redis caching engine. ElastiCache reduces the operational overhead involved in
deploying a distributed caching environment, and provides a way to improve application
load times. For more information, see the 
http://aws.amazon.com/documentation/elasticache/[Amazon ElastiCache documentation^].

=== Elasticsearch

Elasticsearch is a distributed search and analytics engine built on Apache Lucene. Since
its release in 2010, Elasticsearch has quickly become the most popular search engine and
is commonly used for log analytics, full-text search, security intelligence, business
analytics, and operational intelligence use cases.As of version 2.4.3, Magento supports
using Elasticsearch (ES) provided by Amazon Web Services (AWS).


== Security

The AWS Cloud provides a scalable, highly reliable platform that helps customers 
deploy applications and data quickly and securely. +
{blank} +
When you build systems on the AWS infrastructure, security responsibilities are shared
between you and AWS. This shared model can reduce your operational burden as AWS
operates, manages, and controls the components from the host operating system and
virtualization layer down to the physical security of the facilities in which the
services operate. In turn, you assume responsibility and management of the guest
operating system (including updates and security patches), other associated applications,
as well as the configuration of the AWS-provided security group firewall. For more
information about security on AWS, visit the 
http://aws.amazon.com/security/[AWS Security Center^].

=== AWS Identity and Access Management (IAM)

This solution leverages an IAM role with least privileged access. It is not necessary
or recommended to store SSH keys, secret keys, or access keys on the provisioned
instances.

=== OS Security

The root user on cluster nodes can be accessed only by using the SSH key specified
during the deployment process. AWS doesn't store these SSH keys, so if you lose your
SSH key you can lose access to these instances. +
{blank} +
Operating system patches are your responsibility and should be performed on a periodic
basis.

=== Security Groups

A security group acts as a firewall that controls the traffic for one or more
instances. When you launch an instance, you associate one or more security groups
with the instance. You add rules to each security group that allow traffic to or from
its associated instances. You can modify the rules for a security group at any time.
The new rules are automatically applied to all instances that are associated with the
security group. +
{blank} +
The security groups created and assigned to the individual instances as part of this
solution are restricted as much as possible while allowing access to the various functions
needed by Magento. We recommend reviewing security groups to further restrict access as
needed once the cluster is up and running.